# Generated by Django 3.1.4 on 2021-02-04 17:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('profileImage', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=500)),
                ('productRealPrice', models.IntegerField()),
                ('productDiscountedPrice', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='')),
                ('productInformation', ckeditor.fields.RichTextField()),
                ('productTotalQty', models.IntegerField()),
                ('alias', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100)),
                ('orderDate', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('orderTotal', models.CharField(max_length=6)),
                ('modeOfPayment', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amazon.customer')),
                ('products', models.ManyToManyField(to='Amazon.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('dateOrdered', models.DateTimeField(auto_now_add=True)),
                ('orderCompleted', models.BooleanField(default=False)),
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amazon.customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amazon.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amazon.product'),
        ),
    ]
