# Generated by Django 3.1.4 on 2020-12-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(max_length=300)),
                ('productRealPrice', models.IntegerField()),
                ('productDiscountedPrice', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='')),
                ('productInformation', models.TextField()),
                ('productTotalQty', models.IntegerField()),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
    ]
