# Generated by Django 3.1.4 on 2021-01-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
