# Generated by Django 3.1.4 on 2021-01-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0002_auto_20210101_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
