# Generated by Django 3.1.4 on 2020-12-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0003_auto_20201222_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
