# Generated by Django 3.1.4 on 2020-12-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_auto_20201222_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
