# Generated by Django 3.1.4 on 2021-01-26 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_auto_20210103_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productInformation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
