# Generated by Django 3.1.4 on 2021-01-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0005_auto_20210126_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(max_length=500),
        ),
    ]
