# Generated by Django 3.1.4 on 2021-01-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0006_auto_20210126_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100)),
                ('orderDate', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Amazon.customer')),
                ('products', models.ManyToManyField(to='Amazon.Product')),
            ],
        ),
    ]
